<?php

namespace AppBundle\Repository;

/**
 * PostKeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostKeywordRepository extends \Doctrine\ORM\EntityRepository
{
}
